version: "3"

x-logging:
    &default-logging
    logging:
      driver: json-file
      options:
        max-size: 100m

services:
    judge0_server:
        container_name: judge0_server
        image: judge0/judge0:1.13.0
        volumes:
          - ./judge0.conf:/judge0.conf:ro
        ports:
          - "2358:2358"
        privileged: true
        <<: *default-logging
        restart: always

    db:
        image: postgres:13.0
        container_name: judge0_db
        env_file: judge0.conf
        volumes:
          - postgres-data:/var/lib/postgresql/data/
        <<: *default-logging
        restart: always

    redis:
        image: redis:6.0
        container_name: judge0_redis
        command: [
          "bash", "-c",
          'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
        ]
        env_file: judge0.conf
        volumes:
          - redis-data:/data
        <<: *default-logging
        restart: always

    oj-redis:
        image: redis:4.0-alpine
        container_name: oj-redis
        restart: always
        volumes:
          - ./data/redis:/data
  
    oj-postgres:
        image: junhp1234/oj_postgres:latest
        container_name: oj-postgres
        restart: always
        volumes:
          - ./data/postgres:/var/lib/postgresql/data
        environment:
          - POSTGRES_DB=onlinejudge
          - POSTGRES_USER=onlinejudge
          - POSTGRES_PASSWORD=onlinejudge
        ports:
          - "5432:5432"

    judge-server:
        image: junhp1234/judge_server:latest
        container_name: judge-server
        restart: always
        read_only: true
        cap_drop:
          - SETPCAP
          - MKNOD
          - NET_BIND_SERVICE
          - SYS_CHROOT
          - SETFCAP
          - FSETID
        tmpfs:
          - /tmp
        volumes:
          - ./data/backend/test_case:/test_case:ro
          - ./data/judge_server/log:/log
          - ./data/judge_server/run:/judger
        environment:
          - SERVICE_URL=http://judge-server:8080
          - BACKEND_URL=http://oj-backend:8000/api/judge_server_heartbeat/
          - TOKEN=CHANGE_THIS
          - judger_debug=1
    oj-backend:
        image: junhp1234/oj_backend:latest
        #command: /app/start_ssh.sh
        container_name: oj-backend
        restart: always

        depends_on:
          - oj-redis
          - oj-postgres
          - judge-server
        volumes:
          - ./data/backend:/data
        environment:
          - OJ_ENV=production
          - POSTGRES_DB=onlinejudge
          - POSTGRES_USER=onlinejudge
          - POSTGRES_PASSWORD=onlinejudge
          - JUDGE_SERVER_TOKEN=CHANGE_THIS
          # - FORCE_HTTPS=1
          # - STATIC_CDN_HOST=cdn.oj.com
        ports:
          - "0.0.0.0:5555:22"

    oj-frontend:
        image: junhp1234/oj_frontend:latest
        container_name: oj-frontend
        restart: always
        #command: /bin/bash -c "while true; do echo test; sleep 100; done"
        command: sh -c "service ssh start && /bin/bash start_node.sh"
        depends_on:
          - oj-backend
          - judge0_server
        volumes:
          - ./data/frontend:/data
        environment:
                - TARGET=http://oj-backend:8000
                - JUDGE0=http://judge0_server:2358
        ports:
          - "0.0.0.0:5556:22"
          - "0.0.0.0:80:80"
          - "0.0.0.0:443:1443"
        links:
          - "judge0_server"

          
    pgadmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4
        restart: always
        environment:
          PGADMIN_DEFAULT_EMAIL: admin@admin.com
          PGADMIN_DEFAULT_PASSWORD: root
        ports:
          - "5050:80"

volumes:
  postgres-data:
  redis-data: